book/urls.py
from django.urls import path
from . import views  

app_name = "book"
urlpatterns = [
    path('', views.index, name='index'),
    path('tabadd/' , views.tab_add , name="tabadd"),
] 

bookapp/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('book.urls')),
]

book/models.py
from django.db import models
from django.utils import timezone

class Tab(models.Model):
    date = models.DateField(default=timezone.now , unique=True)
    bank = models.FloatField()
    janasevana = models.FloatField()
    borrow = models.FloatField()
    internet = models.FloatField()
    utilities = models.FloatField()
    recharge = models.FloatField()
    inhand = models.FloatField()
    total = models.FloatField()
    def __str__(self):
        return str(self.date)

class Borrow(models.Model):
    name = models.CharField(max_length=100)
    rented = models.IntegerField()
    def __str__(self):
        return self.name

class Balance(models.Model):
    date = models.DateField(default=timezone.now)
    balance = models.FloatField()
    diff = models.FloatField()
    def __str__(self):
        return str(self.date)

book/forms.py
from django import forms

class DateInput(forms.DateInput):
    input_type = 'date'

class TabAdd(forms.Form):
    # date
    date_submitted = forms.DateField(
        widget=DateInput(attrs={
            'class':'form-control',
            'id':'date',
            'placeholder':'Date',
        })
    )
    
    bank = forms.FloatField(
        widget= forms.TextInput(attrs={
            'class' : 'form-control',
            'name' : 'bank',
            'id' : 'bank',
            'placeholder' : 'Bank',
            'onFocus':'this.select();' 
        })
    )

    janasevana = forms.FloatField(
        widget= forms.TextInput(attrs={
            'class' : 'form-control',
            'name' : 'janasevana',
            'id' : 'janasevana',
            'placeholder' : 'Janasevana',
            'onFocus':'this.select();'
        })
    )
    borrow = forms.FloatField(
        widget= forms.TextInput(attrs={
            'class' : 'form-control',
            'name' : 'borrow',
            'id' : 'borrow',
            'placeholder' : 'Borrow',
            'onFocus':'this.select();'
        })
    )
    internet = forms.FloatField(
        widget= forms.TextInput(attrs={
            'class' : 'form-control',
            'name' : 'internet',
            'id' : 'internet',
            'placeholder' : 'Internet',
            'onFocus':'this.select();'
        })
    )
    utilities = forms.FloatField(
        widget= forms.TextInput(attrs={
            'class' : 'form-control',
            'name' : 'utilities',
            'id' : 'utilities',
            'placeholder' : 'Utilities',
            'onFocus':'this.select();'
        })
    )
    recharge = forms.FloatField(
        widget= forms.TextInput(attrs={
            'class' : 'form-control',
            'name' : 'recharge',
            'id' : 'recharge',
            'placeholder' : 'Recharge',
            'onFocus':'this.select();'
        })
    )
    inhand = forms.FloatField(
        widget= forms.TextInput(attrs={
            'class' : 'form-control',
            'name' : 'inhand',
            'id' : 'inhand',
            'placeholder' : 'Inhand',
            'onFocus':'this.select();'
        })
    )
    
    

 

book/views.py
from django.shortcuts import render ,HttpResponse ,redirect
from django.db.models import Sum
from datetime import date, timedelta , datetime
from itertools import chain
from decimal import Decimal
from .models import Tab ,Balance , Borrow
from .forms import TabAdd

# Create your views here.

def index(request):
    data = Balance.objects.order_by("date").reverse()
    last_seven = Balance.objects.order_by("date").reverse()[:7]
    yesterday = date.today() - timedelta(days = 1)
    last_balance = Balance.objects.filter(date=yesterday).values_list("balance", flat=True)
    total_profit = Balance.objects.aggregate(Sum('diff'))
    total_debt = Borrow.objects.aggregate(Sum('rented'))
    context = {'data':data , 'last_seven':last_seven , 'total_profit':total_profit , 'total_debt':total_debt , 'last_balance':last_balance , 'yesterday':yesterday}
    return render(request , 'book/index.html', context)

def tab_add(request):
    data = Tab.objects.order_by("date").reverse()[:1]
    last_date = Tab.objects.latest('date')
    last_total = Tab.objects.latest('total')
    if str(last_date) == str(date.today()): 
        print("hekl" + str(last_date) + "." + str(date.today()))
        form_not_valid = True
    else:
        form_not_valid = False
    adddata = 23
    if request.method == 'POST':
        form = TabAdd(request.POST)
        

        if form.is_valid():
            date_not_enter = False
            date_not_allowed = False
            form_added = False
            date_old = datetime.strptime(request.POST['date_submitted'] , "%Y-%m-%d").date()
            old = date_old - timedelta(days=1)
            last_date_new = datetime.strptime(str(last_date) , "%Y-%m-%d").date()
            new_add = str(last_date_new + timedelta(days=1))
            adddata = form.cleaned_data['bank'] + form.cleaned_data['janasevana'] + form.cleaned_data['borrow'] + form.cleaned_data['internet'] + form.cleaned_data['utilities'] + form.cleaned_data['recharge'] + form.cleaned_data['inhand']
            diff = float(adddata)-data[0].total
            print(data[0].total)
            if request.POST['date_submitted'] > str(date.today()):
                date_not_allowed = True
                context = {'data':data ,'form':form , 'form_not_valid':form_not_valid , 'date_not_allowed' : date_not_allowed } 
                return render(request , 'book/tab_add.html' , context)
            elif str(last_date) != str(old) and str(old) > str(last_date): 
                date_not_enter = True 
                context = {'data':data ,'form':form , 'form_not_valid':form_not_valid , 'new_add' : new_add , 'date_not_enter':date_not_enter } 
                return render(request , 'book/tab_add.html' , context)
            else:
                datas = Tab(date = request.POST['date_submitted'],bank = request.POST['bank'], janasevana = request.POST['janasevana'] , borrow = request.POST['borrow'] , internet = request.POST['internet'] , utilities = request.POST['utilities'] , recharge = request.POST['recharge'] , inhand = request.POST['inhand'] , total = adddata)
                datas.save()
                print("add" + str(float(str(adddata))) + " data"+ str(float(str(data[0].total))))
                data1 = Balance(date = request.POST['date_submitted'] , balance = adddata , diff = diff) 
                data1.save()
                form_added = True
                # return HttpResponse(diff) 
                context = {'data':data ,'form':form , 'form_not_valid':form_not_valid , 'form_added': form_added } 
                return render(request , 'book/tab_add.html' , context)
    else:
        form = TabAdd()    
    context = {'data':data ,'form':form , 'form_not_valid':form_not_valid } 
    return render(request , 'book/tab_add.html' , context)

book/templates/book/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">


<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Bookapp</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="{% static 'vendors/mdi/css/materialdesignicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/css/vendor.bundle.base.css' %}">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <!-- endinject -->
    <!-- Layout styles -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- End layout styles -->
    <link rel="shortcut icon" href="{% static 'images/favicon.png' %}">
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <style type="text/css">
        /* Chart.js */
        @keyframes chartjs-render-animation {
            from {
                opacity: .99
            }

            to {
                opacity: 1
            }
        }

        .chartjs-render-monitor {
            animation: chartjs-render-animation 1ms
        }

        .chartjs-size-monitor,
        .chartjs-size-monitor-expand,
        .chartjs-size-monitor-shrink {
            position: absolute;
            direction: ltr;
            left: 0;
            top: 0;
            right: 0;
            bottom: 0;
            overflow: hidden;
            pointer-events: none;
            visibility: hidden;
            z-index: -1
        }

        .chartjs-size-monitor-expand>div {
            position: absolute;
            width: 1000000px;
            height: 1000000px;
            left: 0;
            top: 0
        }

        .chartjs-size-monitor-shrink>div {
            position: absolute;
            width: 200%;
            height: 200%;
            left: 0;
            top: 0
        }
    </style>
</head>

<body>
    <div class="container-scroller">
        <!-- partial:partials/_navbar.html -->
        <nav class="navbar default-layout-navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
            <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
                <a class="navbar-brand brand-logo" href="index.html">
                    <h1 class="display-3 text-success">BookApp</h1>
                </a>
                <a class="navbar-brand brand-logo-mini" href="index.html">
                    <h1 class="display-2 text-success">B</h1>
                </a>
            </div>
            <div class="navbar-menu-wrapper d-flex align-items-stretch">
                <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
                    <span class="mdi mdi-menu"></span>
                </button>
                <ul class="navbar-nav navbar-nav-right">
                    <li class="nav-item d-none d-lg-block full-screen-link">
                        <a class="nav-link">
                            <i class="mdi mdi-fullscreen" id="fullscreen-button"></i>
                        </a>
                    </li>
                    <li class="nav-item nav-profile dropdown">
                        <a class="nav-link dropdown-toggle" id="profileDropdown" href="#" data-toggle="dropdown"
                            aria-expanded="false">
                            <div class="nav-profile-img">
                                <img src="{% static 'images/faces/face1.jpg' %}" alt="image">
                                <span class="availability-status online"></span>
                            </div>
                            <div class="nav-profile-text">
                                <p class="mb-1 text-black">Joyal Jose Scaria</p>
                            </div>
                        </a>
                        <div class="dropdown-menu navbar-dropdown" aria-labelledby="profileDropdown">
                            <a class="dropdown-item" href="#">
                                <i class="mdi mdi-cached mr-2 text-success"></i> Activity Log </a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">
                                <i class="mdi mdi-logout mr-2 text-primary"></i> Signout </a>
                        </div>
                    </li>
                </ul>
                <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button"
                    data-toggle="offcanvas">
                    <span class="mdi mdi-menu"></span>
                </button>
            </div>
        </nav>
        <!-- partial -->
        <div class="container-fluid page-body-wrapper">
            <!-- partial:partials/_sidebar.html -->
            <nav class="sidebar sidebar-offcanvas" id="sidebar">
                <ul class="nav">
                    <li class="nav-item nav-profile">
                        <a href="#" class="nav-link">
                            <div class="nav-profile-image">
                                <img src="{% static 'images/faces/face1.jpg' %}" alt="profile">
                                <span class="login-status offline"></span>
                                <!--change to offline or busy as needed-->
                            </div>
                            <div class="nav-profile-text d-flex flex-column">
                                <span class="font-weight-bold mb-2">Joyal Jose Scaria </span>
                                <!-- <span class="text-secondary text-small">Project Manager</span> -->
                            </div>
                            <i class="mdi mdi-bookmark-check text-success nav-profile-badge"></i>
                        </a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="index.html">
                            <span class="menu-title">Dashboard</span>
                            <i class="mdi mdi-home menu-icon"></i>
                        </a>
                    </li>


                    <!-- <li class="nav-item">
                        <a class="nav-link" href="pages/icons/mdi.html">
                            <span class="menu-title">Icons</span>
                            <i class="mdi mdi-contacts menu-icon"></i>
                        </a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="pages/tables/basic-table.html">
                            <span class="menu-title">Tables</span>
                            <i class="mdi mdi-table-large menu-icon"></i>
                        </a>
                    </li> -->
                </ul>
            </nav>
            <!-- partial -->
            {% block content %}
            {% endblock %}
            <!-- main-panel ends -->
        </div>
        <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <!-- plugins:js -->
    <script src="{% static 'vendors/js/vendor.bundle.base.js' %}"></script>
    <!-- endinject -->
    <!-- Plugin js for this page -->
    <script src="{% static 'vendors/chart.js/Chart.min.js' %}"></script>
    <!-- End plugin js for this page -->
    <!-- inject:js -->
    <script src="{% static 'js/off-canvas.js' %}"></script>
    <script src="{% static 'js/hoverable-collapse.js' %}"></script>
    <script src="{% static 'js/misc.js' %}"></script>
    <!-- endinject -->
    <!-- Custom js for this page -->
    <!-- <script src="{% static 'js/dashboard.js' %}"></script> -->
    <script src="{% static 'js/todolist.js' %}"></script>
    <!-- End custom js for this page -->
    <script src="{% static 'js/site.js' %}"></script>

    <script>
        var date = [
            {% for bal in last_seven %}
                '{{bal.date}}',
            {%endfor%}
        ]
        var values = [
            {% for bal in last_seven %}
                {{bal.diff}} ,
            {%endfor%}
        ]
        var ctx = document.getElementById('visit-sale-chart').getContext('2d');
        var myChart = new Chart(ctx, {
            type: 'line',
            data: {
                labels: date.reverse(),
                datasets: [{
                    label: 'Rs of Profit',
                    data: values.reverse(),
                    backgroundColor: [
                        'rgba(182, 109, 255, 0.2)',
                        'rgba(54, 162, 235, 0.2)',
                        'rgba(255, 206, 86, 0.2)',
                        'rgba(75, 192, 192, 0.2)',
                        'rgba(153, 102, 255, 0.2)',
                        'rgba(255, 159, 64, 0.2)'
                    ],
                    borderColor: [
                        'rgba(182, 109, 255, 1)',
                        'rgba(54, 162, 235, 1)',
                        'rgba(255, 206, 86, 1)',
                        'rgba(75, 192, 192, 1)',
                        'rgba(153, 102, 255, 1)',
                        'rgba(255, 159, 64, 1)'
                    ],
                    borderWidth: 1
                }]
            },
            options: {
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero: true
                        }
                    }]
                }
            }
        });
    </script>

</body>

</html>

book/templates/book/index.html
{% extends 'book/base.html' %}
{% load staticfiles %}
{% block content %}

<div class="main-panel">
    <div class="content-wrapper">
        <div class="row">
            <div class="col-md-4 stretch-card grid-margin">
                <div class="card bg-gradient-danger card-img-holder text-white">
                    <div class="card-body">
                        <img src="{% static 'images/dashboard/circle.svg' %}" class="card-img-absolute"
                            alt="circle-image">
                        <h4 class="font-weight-normal mb-3">Total<i
                                class="mdi mdi-arrow-up-bold-circle mdi-24px float-right"></i>
                        </h4>
                        <h2 class="mb-5">₹ {{total_profit.diff__sum}}</h2>
                    </div>
                </div>
            </div>
            <div class="col-md-4 stretch-card grid-margin">
                <div class="card bg-gradient-info card-img-holder text-white">
                    <div class="card-body">
                        <img src="{% static 'images/dashboard/circle.svg' %}" class="card-img-absolute"
                            alt="circle-image">
                        <h4 class="font-weight-normal mb-3">Total Debt <i
                                class="mdi mdi-arrow-down-bold-circle mdi-24px float-right"></i>
                        </h4>
                        <h2 class="mb-5">₹ {{total_debt.rented__sum}}</h2>
                    </div>
                </div>
            </div>
            <div class="col-md-4 stretch-card grid-margin">
                <div class="card bg-gradient-success card-img-holder text-white">
                    <div class="card-body">
                        <img src="{% static 'images/dashboard/circle.svg' %}" class="card-img-absolute"
                            alt="circle-image">
                        <h4 class="font-weight-normal mb-3"> {{yesterday}} Balance<i
                                class="mdi mdi-diamond mdi-24px float-right"></i>
                        </h4>
                        <h2 class="mb-5">
                            {% for lbal in last_balance %}
                            ₹ {{lbal}}
                            {% endfor %}
                        </h2>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <div class="chartjs-size-monitor">
                            <div class="chartjs-size-monitor-expand">
                                <div class=""></div>
                            </div>
                            <div class="chartjs-size-monitor-shrink">
                                <div class=""></div>
                            </div>
                        </div>
                        <div class="clearfix">
                            <h4 class="card-title float-left">Last Seven Days Profit Chart</h4>
                        </div>
                        <canvas id="visit-sale-chart" class="mt-4 chartjs-render-monitor"
                            style="display: block; width: 391px; height: 195px;" width="391" height="195"></canvas>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12 grid-margin">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Recent Tickets</h4>
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th> Date </th>
                                        <th> Balance </th>
                                        <th> Earnings </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for bal in data %}
                                    <tr>
                                        <td>{{bal.date}}</td>
                                        <td>₹{{bal.balance}}</td>
                                        <td>
                                            <label class="badge badge-gradient-success">₹ {{bal.diff}}</label>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- partial -->
</div>
{% endblock %}

book/templates/book/tab_add.html
{% extends 'book/base.html' %}
{% load staticfiles %}
{% block content %}

<style>
    .alert{
        padding: 0;
    }

    .errorlist
    {
        margin-top: 1rem;
    }

    .alert ul 
    {
        list-style-type: none;
    }
    .date_not_enter
    {
        padding-top: 10px;
        padding-bottom: 10px;
        padding-left: 20px;
    }
</style>

<div class="main-panel">
    <div class="content-wrapper">
        {% if date_not_enter %} <h6 class="alert alert-success date_not_enter">{{new_add}} is not enterd </h6> {% endif %}
        {% if date_not_allowed %} <h6 class="alert alert-success date_not_enter">Entry For This Date is Not Allowed</h6> {% endif %}
        {% if form_added %} <h6 class="alert alert-info date_not_enter"> 
        {% for dat in data %}
            {{dat.date}}
        {% endfor %}
             Metrics Added Successfully</h6> {% endif %}
        <div class="row">
            <div class="col-md-6  grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Add Metrics</h4>
                        <p class="card-description"> Enter Basic Metrics for Calculations </p>
                        <form class="forms-sample" method="POST" action="{% url 'book:tabadd' %}" id="form1">
                            {% csrf_token %}
                            {{ form.non_field_errors }}
                            <div class="form-group">
                                {{form.date.errors}}
                                <label for="date">Date</label>
                                {{form.date_submitted}}
                                <!-- <input type="date" class="form-control" id="date" placeholder="Date"> -->
                            </div>

                            <div class="form-group">
                                {% if form.bank.errors %}
                                    <h3 class="alert alert-danger">{{form.bank.errors}}</h3>
                                {% endif %}
                                <label for="bank">Bank</label>
                                {{form.bank}}
                                <!-- <input type="text" name="bank" id="bank" class="form-control"
                                    value="{% for dat in data %} {{dat.bank}} {% endfor %}"  onFocus="this.select();"> -->
                            </div>


                            <div class="form-group">
                                <label for="janasevana">Janasevana</label>
                                {{form.janasevana}}
                                <!-- <input type="text" name="janasevana" id="janasevana" class="form-control" -->
                                    <!-- value="{% for dat in data %} {{dat.janasevana}} {% endfor %}" onFocus="this.select();"> -->
                            </div>


                            <div class="form-group">
                                <label for="borrow">Borrow</label>
                                {{form.borrow}}
                                <!-- <input type="text" name="borrow" id="borrow" class="form-control"
                                    value="{% for dat in data %} {{dat.borrow}} {% endfor %}" onFocus="this.select();"> -->
                            </div>


                            <div class="form-group">
                                <label for="internet">Internet</label>
                                {{form.internet}}
                                <!-- <input type="text" name="internet" id="internet" class="form-control"
                                    value="{% for dat in data %} {{dat.internet}} {% endfor %}" onFocus="this.select();"> -->
                            </div>

                            <div class="form-group">
                                <label for="utilities">Utilities</label>
                                {{form.utilities}}
                                <!-- <input type="text" name="utilities" id="utilities" class="form-control"
                                    value="{% for dat in data %} {{dat.utilities}} {% endfor %}" onFocus="this.select();"> -->
                            </div>

                            <div class="form-group">
                                <label for="recharge">Recharge</label>
                                {{form.recharge}}
                                <!-- <input type="text" name="recharge" id="recharge" class="form-control" -->
                                <!-- value="{% for dat in data %} {{dat.recharge}} {% endfor %}" onFocus="this.select();"> -->
                            </div>

                            <div class="form-group">
                                <label for="inhand">Inhand</label>
                                {{form.inhand}}
                                <!-- <input type="text" name="inhand" id="inhand" class="form-control"
                                value="{% for dat in data %} {{dat.inhand}} {% endfor %}" onFocus="this.select();"> -->
                            </div>


                            <button type="submit" id="cbutton" class="btn btn-gradient-primary mr-2" onClick="addVal()">Add Metrics</button>
                        </form>
                    </div>
                </div>
            </div>

            <div class="col-md-6 grid-margin ">
                <div class="card">
                    {{last_date}}
                    <div class="card-body">
                        <h4 class="card-title">
                            {%for dat in data %}
                            {{dat.date}}
                            {% endfor %} Metrics
                        </h4>
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th class="font-weight-bold"> Metric </th>
                                        <th class="font-weight-bold"> Amount </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td id="{{forloop.counter}}lis">Bank</td>
                                        <td id="{{forloop.counter}}val">₹ {% for dat in data %} {{dat.bank}} {% endfor %}</td>
                                    </tr>
                                    <tr>
                                        <td id="{{forloop.counter}}lis">Janasevana</td>
                                        <td id="{{forloop.counter}}val">₹ {% for dat in data %} {{dat.janasevana}} {% endfor %}</td>
                                    </tr>
                                    <tr>
                                        <td id="{{forloop.counter}}lis">Borrow</td>
                                        <td id="{{forloop.counter}}val">₹ {% for dat in data %} {{dat.borrow}} {% endfor %}</td>
                                    </tr>
                                    <tr>
                                        <td id="{{forloop.counter}}lis">Internet</td>
                                        <td id="{{forloop.counter}}val">₹ {% for dat in data %} {{dat.internet}} {% endfor %}</td>
                                    </tr>
                                    <tr>
                                        <td id="{{forloop.counter}}lis">Utilities</td>
                                        <td id="{{forloop.counter}}val">₹ {% for dat in data %} {{dat.utilities}} {% endfor %}</td>
                                    </tr>
                                    <tr>
                                        <td id="{{forloop.counter}}lis">Recharge</td>
                                        <td id="{{forloop.counter}}val">₹ {% for dat in data %} {{dat.recharge}} {% endfor %}</td>
                                    </tr>
                                    <tr>
                                        <td id="{{forloop.counter}}lis">Inhand</td>
                                        <td id="{{forloop.counter}}val">₹ {% for dat in data %} {{dat.inhand}} {% endfor %}</td>
                                    </tr>
                                    <tr>
                                        <td id="{{forloop.counter}}lis" class="font-weight-bold text-uppercase">Total</td>
                                        <td id="{{forloop.counter}}val" class="font-weight-bold">₹ {% for dat in data %} {{dat.total}} {% endfor %}</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

<script>
    document.getElementById('bank').value = "{% for dat in data %} {{dat.bank}} {% endfor %}"
    document.getElementById('janasevana').value = "{% for dat in data %} {{dat.janasevana}} {% endfor %}"
    document.getElementById('borrow').value = "{% for dat in data %} {{dat.borrow}} {% endfor %}"
    document.getElementById('internet').value = "{% for dat in data %} {{dat.internet}} {% endfor %}"
    document.getElementById('utilities').value = "{% for dat in data %} {{dat.utilities}} {% endfor %}"
    document.getElementById('recharge').value = "{% for dat in data %} {{dat.recharge}} {% endfor %}"
    document.getElementById('inhand').value = "{% for dat in data %} {{dat.inhand}} {% endfor %}"
    
    {% if form_not_valid %}
        console.log("hai");
        $("#form1 :input").attr("disabled", true);
    {% endif %}

    $('.date_not_enter').delay(5000).fadeOut('slow');

</script>
{% endblock %}